### ISSUE TITLE
[1.20.1-Forge] Crash when booting game. 

### ISSUE THREAD

**Issue by Gbergz** [Ultreon/exit-confirmation#13]
**To Reproduce**
1. Install mod on 1.20.1
2. Launch game
3. Game crashed

**Logs**
https://gist.githubusercontent.com/Gbergz/1db8386e91c2f20b678f5395e41fda8e/raw/2c758b796c35ea26605e6a98332ca630b9374f42/gistfile1.txt

**Crash report**
Wasn't generated.

**Please complete the following information:**
 - OS: Windows 11
 - Minecraft version: 1.20.1
 - Mod Version: 2.4.2

**FOR FORGE:**
 - Forge version: 47.1.0

**Additional context**
None.

**Additional mods used**
None.

**Comment by QboiDev** [comment]
Hmm, seems like a known issue, not reported yet tho.
2.5.0 is going to have the fix (alongside a new feature)

**Comment by QboiDev** [comment]
If I recall correctly this is fixed. Let me know if it still occurs.
