### ISSUE TITLE
Mod doesn't work on my modpack :/

### ISSUE THREAD

**Issue by xFirefalconx** [Ultreon/exit-confirmation#16]
**Describe the bug**
Basically, the mod doesn't do anything. I just looked at the config in case I missed something but all is set to true so... uh why does it close when I press 'x' on my window, when I press "quit" in main menu... no reaction from the mod like it's being suppressed. Which is likely, given the amount of mods. 

**To Reproduce**
1. Install my Modpack, its name is Royal Equines: Petrified Magic (version 1.1b05)
2. Add exit confirmation
3. Launch the game
4. Click on one exit option
5. The game closes without a confirmation popping up (tested so far with version 1.1b05 of my pack and by clicking on quit game in the main menu, but the 'x' button should also not show the exit confirmation)

**Expected behavior**
I click on 'x' or 'quit' and get asked whether that's what I wanted.

**Screenshots**
N/A

**Please complete the following information:**
 - OS: [Windows]
 - Minecraft version [1.18.2]
 - Devices Mod Version: [1.01]

**FOR FORGE:**
 - Forge version [40.2.9, 40.2.14]

**Additional context**

I noticed this after editing my pack for the next version, hence... It's a bunch of mods potentially interfering. But even the updated ones I currently am working on don't *seem* to change that fact. Use this info as a cautious direction. I am a bit behind updating my mods.

**Comment by QboiDev** [comment]
I think I will test it without the modpack first. I sometimes break my own mods by accident lmao.

**Comment by QboiDev** [comment]
Ok, can confirm the mod doesn't even do it without the modpack. :skull:
Escape on title screen does work tho. I think it's just because it's a really old version I guess.

**Comment by QboiDev** [comment]
Ok, gonna backport the features back to 1.18.2

**Comment by QboiDev** [comment]
Can you confirm this versions works? https://modrinth.com/mod/exit-confirmation/version/1.0.2+mc.1.18.1-forge
Gonna upload to CurseForge later, tho keep in mind that CurseForge takes a while to accept mods sometimes. So it might take a few days in some cases.

**Comment by xFirefalconx** [comment]
Thanks for your fast reply! (Ngl I had to laugh when I read your messages, I break my own stuff way too often, too.) 
I downloaded the Modrinth version and it works when I click on the Quit or X button. I have some requests for the positioning though, but... I should open a new issue for that, correct?

**Comment by QboiDev** [comment]
Yea, you can make a new issue for that. I also uploaded versions for 1.17.1, 1.16.5 and 1.8.9 btw.
Also, some might not know, but I get notifications for issues on GitHub almost instantly thru Discord. I've set up webhooks for that. (Useful for reacting quickly)
