### ISSUE TITLE
UI enhancement request - custom offset or alignment types

### ISSUE THREAD

**Issue by xFirefalconx** [Ultreon/exit-confirmation#17]
**Is your feature request related to a problem? Please describe.**

When I open up the exit confirmation window in my modpack, it's... not so conveniently aligned and even a bit hard to read. See screenshot. (My inner monk is screaming at the alignments in Pause Screen)

**Describe the solution you'd like**

I'd love either of those: 
a.1) a percentage of screen offset for the top of the window and the possibility to add a (transparency supproted) background image to the exit confirmation. 
a.2) the option to align it to the screen center, and also to add a custom (transparency supported) background image to the exit confirmation.
b) Maybe even go that far to optionally set one for every screen, but make it overridden by a current value by default. 

(I prefer a.1) + b) )

**Describe alternatives you've considered (optional, but recommended)**

Beat my inner monk to be silent :'D No, I have no idea tbh. FancyMenu also shows when I hover over its buttons while having the exit confirmation open which is a bit cringe. I think a PNG alone might make a difference. With the current setup as a fallback if there's none or it's invalid (would also appreciate a log message if it can't be found).

**Additional context**

![grafik](https://github.com/Ultreon/exit-confirmation/assets/106652912/69912c4e-d4b3-4dec-ad70-538c3e85a46a)
![grafik](https://github.com/Ultreon/exit-confirmation/assets/106652912/01470be6-e4ea-4c40-979b-195779260366)
![grafik](https://github.com/Ultreon/exit-confirmation/assets/106652912/81f99341-9720-4039-87ac-6f9cfc727f72)

Oh no, the buttons below are hoverable (using FancyMenu) :/ (I tested and could click multiple ones which once also led the game to crash, report incoming)
![grafik](https://github.com/Ultreon/exit-confirmation/assets/106652912/1d6c0ba4-5df5-41e3-a3e9-4680007674a1)

**Comment by QboiDev** [comment]
If I would do a.1) and b) I think i need to add a library for cross-game and cross-version support. (Yes this mod supports other games that are in Java and moddable)
Mostly because of the different config apis and such...

**Comment by xFirefalconx** [comment]
I see, so it'd be a bigger task to add. I assume technically you cannot just take the current screen resolution and move the fields down by a certain percentage, correct?

Ah, configs. The fun stuff everybody loves x) I understand. Would you give it a try or rather no?

**Comment by QboiDev** [comment]
Well, I don't mind adding that extra library to do it. But it wouldn't be .toml files then. Probably one of .json, .json5, .properties or .ubo.

**Comment by QboiDev** [comment]
Probably would need to make it 3.x.x since the breaking change in config.
(Major versions are breaking changes, minor versions are features, and patch versions are bugfixes)

**Comment by xFirefalconx** [comment]
Yeah I don't mind, I use Configured for in-game changes but I can also just open up the config in Editor or VSCode so I don't mind (though in-game crashes because I clicked the config button are always a bit... meh xD) 
I just hope I can edit and reload the configs somehow without having to restart the pack each time, that eats lots of time (my pack needs 4-7 min to load each time)

**Comment by QboiDev** [comment]
Also, .ubo is off the list since it's a binary file, and that would require in-game config. Woops :flushed:

**Comment by QboiDev** [comment]
Bruh there isn't really any official type defined configuration type. I guess I'm gonna make my own lmao.

**Comment by xFirefalconx** [comment]
Alright then :'D keep me updated, please!

**Comment by QboiDev** [comment]
LMAO accidentally tried to create a programming language instead :rofl:

**Comment by xFirefalconx** [comment]
Alright then :'D keep me updated, please! (Didn't just post the same reply, nono)

**Comment by QboiDev** [comment]
I'm moving to https://gitlab.com/ultreon/mods/exit-confirmation now.
