### ISSUE TITLE
FancyMenu button clickable, in some cases causes the game to crash...

### ISSUE THREAD

**Issue by xFirefalconx** [Ultreon/exit-confirmation#18]
**To Reproduce**

approach a)
1. Install both FancyMenu (+dependencies) and exit confirmation
2. Start pack
3. Make one FancyMenu button link to a custom GUI 
4. Open the exit screen in the window with the custom GUI linked button
5. click the button
6. Game should crash?

if that is no problem
approach b)
1. Install my modpack :'D (Royal Equines: Petrified Magic (version 1.1b05, aka the latest availabe on CF as of today))
2. Add exit confirmation 1.0.2 to it
3. Start game
4. Click on the "Modpack Tutorial" button
5. Open exit screen by clicking "x" on the window top
6. Press on the "Starter's Guide" button
7. Game should crash.

**Logs**
Add an optional log file to the issue, this helps developers to find out when it went wrong.

[latest.log](https://github.com/Ultreon/exit-confirmation/files/13515917/latest.log)

**Crash report**
Add a crash report to the issue, this is essential for developers to know what went wrong.

[crash-2023-11-30_17.23.22-client.txt](https://github.com/Ultreon/exit-confirmation/files/13515932/crash-2023-11-30_17.23.22-client.txt)
[crash-2023-11-30_17.32.58-client.txt](https://github.com/Ultreon/exit-confirmation/files/13515933/crash-2023-11-30_17.32.58-client.txt)

**Please complete the following information:**
 - OS: [Windows]
 - Minecraft version [1.18.2]
 - Devices Mod Version: [1.0.2]

**FOR FORGE:**
 - Forge version [40.2.14]

**Additional context**
All buttons are sort of clickable. At least those modified by FancyMenu. If it's a linked issue maybe reach out to Keksuccino, its developer. 
Screenshots can be found here https://github.com/Ultreon/exit-confirmation/issues/17

**Additional mods used**
Optionally, give a list of mods used (as long it isn't many).
I am assuming here, FancyMenu alone. 
Let me know if this alone causes no issues. See crash log(s) for further information, there is a full mod list attached (though I am on version 1.1b06, the unreleased version of my modpack so the list is EVEN LONGER. Sorry about that lol).

**Comment by QboiDev** [comment]
I'm moving to https://gitlab.com/ultreon/mods/exit-confirmation now.
If you want you can copy+paste the issue there.
