### ISSUE TITLE
Config menu?

### ISSUE THREAD

**Issue by Scarlaid** [Ultreon/exit-confirmation#4]
I don't really like the narrator talk to me whenever I want to exit Minecraft, mainly because the option menu is already there so the narrator is kinda useless, unless taskkill

Will there a config menu to turn on/off this mod instead of uncheck this mod and then re-run the game?

**Comment by QboiDev** [comment]
You can use Configured for managing the config in-game.
There's a config file you can manually edit if you want that instead.
I can however make a toggle for the narration at some point.

**Comment by Scarlaid** [comment]
I think I would prefer a configuration menu open via Mod Menu more, I don't seem to see it
yet I don't know what "Configured" you mentioned is...

**Comment by QboiDev** [comment]
Configured is a mod that adds config screens to mods that use a supported config library.
It's for [Forge](https://curseforge.com/minecraft/mc-mods/configured) and [Fabric](https://curseforge.com/minecraft/mc-mods/configured-fabric).

**Comment by QboiDev** [comment]
I can add a config screen, but then I rather would use my library mod for making the GUI, meaning it would have another dependency. And I want this mod to have as few dependencies as possible.

**Comment by Scarlaid** [comment]
yeah configured isn't on 1.19.4 yet so I guess I have to wait 😥

**Comment by QboiDev** [comment]
Done for 1.20, not sure if I will backport it to 1.19.4 tho.

**Comment by Scarlaid** [comment]
some might be still on 1.19.4 because lack of mod supports ig,
1.20 just came out tho
