### ISSUE TITLE
Add confirm exit on world/server quit

### ISSUE THREAD

**Issue by JustAlittleWolf** [Ultreon/exit-confirmation#8]
Update to 1.20.1

**Comment by QboiDev** [comment]
Already planned

**Comment by Felix14-v2** [comment]
Doesn't [1.20 version](https://modrinth.com/mod/exit-confirmation/version/2.4.0-fabric) just work?

**Comment by JustAlittleWolf** [comment]
Confirm quitting world doesn't work.

**Comment by Felix14-v2** [comment]
Then this issue should be renamed and described to clarify this and other things to be done before the update to the new version
If you've noticed any other broken things, please, list them as well

**Comment by QboiDev** [comment]
> Confirm quitting world doesn't work.

@JustAlittleWolf When does this happen? Is this when you change the version in the mod metadata?

**Comment by JustAlittleWolf** [comment]
@Qboi123 I didn't change the metadata, I just used the newest 1.20 build on modrinth in 1.20.1 I thought it was a version issue. Mod Version used is 2.4.0.

**Comment by QboiDev** [comment]
I think the mod would prevent running on newer minor versions like 1.20.1
At least that's what I tried to do.

**Comment by JustAlittleWolf** [comment]
> I think the mod should prevent running on newer minor versions like 1.20.1

Oh maybe I did change the fabric.mod.json then haha

**Comment by QboiDev** [comment]
Well, doesn't seem like 1.20.1 need any change in the code to make it work out of the box.

**Comment by JustAlittleWolf** [comment]
Yeah I don't think there were any breaking changes in 1.20.1 in general

**Comment by QboiDev** [comment]
Also, I don't remember the mod asking for confirmation when quitting the world. Only when closing the game in some way or another. (Except killing the process ofc)

**Comment by JustAlittleWolf** [comment]
Oh, it does say that it has that feature on the modrinth page though.

**Comment by JustAlittleWolf** [comment]
There is also a config option for it

**Comment by QboiDev** [comment]
> including close prompt when using escape in title screen, when in-game and quit button

Showing the close prompt when closing the game when in-game. Like pressing Alt+F4 while mining for platinum for example.

**Comment by JustAlittleWolf** [comment]
Oh

**Comment by QboiDev** [comment]
Might need to phrase that better since the quit button is meant the quit button in the title screen.

**Comment by JustAlittleWolf** [comment]
Could you include that as a feature then? :)

**Comment by JustAlittleWolf** [comment]
> Might need to phrase that better since the quit button is meant the quit button in the title screen.

Yeah that confused me, I think the ingame return to menu button also says "Quit World" or something similar

**Comment by QboiDev** [comment]
> Could you include that as a feature then? :)

Maybe
